#!/usr/bin/env python 
# -*- coding: utf-8 -*-"
"""Fade - is a tool that provides you and your network optimal security. 
It monitors keyloggers, ddos attacks, and much more. 
Fade also allows you to catch, trap, and back fire on those killing or interrupting your network through secure 
and fast ICMP Flood Attacks, high powered DDOS Attacks, and much more!
"""
from source.scripts.fade import Fade 

# Run fade
if __name__ == "__main__":
	app = Fade()
